backend:
  name:git-gateway
  branch:main

media_folder:"uploads"
public_folder:"/uploads"

collections:
  - name:"posts"
    label:"Posts"
    folder:"posts"
    create: true
    slug:"{{slug}}"
    fields:
      - { label:"Title", name: "title", widget: "string" }
      - { label:"Category", name:"category", widget:"select", options:["Newsroom", "Stupid Advise", "Stupid Fashion", "Wild Ideas"] }
      - { label:"Body", name:"body", widget:"markdown" }
      - { label:"Image", name:"image", widget:"image", required:false }
